# Generated by Django 5.2 on 2025-05-11 23:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='action',
            field=models.ManyToManyField(blank=True, to='app.subscribeparam', verbose_name='tasks_for_ad'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 11, 23, 14, 52, 426200, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='template',
            name='voting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_voting', to='app.votingparam', verbose_name='tasks_for_voting'),
        ),
    ]
