# Generated by Django 5.2 on 2025-05-11 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_task_action_alter_task_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 11, 23, 14, 54, 971911, tzinfo=datetime.timezone.utc)),
        ),
    ]
