# Generated by Django 5.2 on 2025-05-11 23:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_task_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='channel_link',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Ссылка на канал'),
        ),
        migrations.AlterField(
            model_name='task',
            name='sessions',
            field=models.ManyToManyField(blank=True, to='app.sessions', verbose_name='Сессии'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Название шаблона'),
        ),
    ]
