# Generated by Django 5.2 on 2025-05-11 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_task_channel_link_alter_task_sessions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyparam',
            name='reaction_ladder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_reaction_ladder', to='app.ladder', verbose_name='Лесенка реакций'),
        ),
        migrations.AlterField(
            model_name='historyparam',
            name='view_ladder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_view_ladder', to='app.ladder', verbose_name='Лесенка просмотров'),
        ),
        migrations.AlterField(
            model_name='reactionparam',
            name='start_ladder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ladder', verbose_name='Лесенка к старту'),
        ),
        migrations.AlterField(
            model_name='subscribeparam',
            name='start_ladder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_start_ladder', to='app.ladder', verbose_name='Лесенка к старту'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subscribe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_subscribe', to='app.subscribeparam', verbose_name='tasks_for_subscribe'),
        ),
        migrations.AlterField(
            model_name='task',
            name='view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_view', to='app.viewparam', verbose_name='tasks_for_view'),
        ),
        migrations.AlterField(
            model_name='template',
            name='subscribe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_subscribe', to='app.subscribeparam', verbose_name='tasks_for_subscribe'),
        ),
        migrations.AlterField(
            model_name='template',
            name='view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_view', to='app.viewparam', verbose_name='tasks_for_view'),
        ),
        migrations.AlterField(
            model_name='viewparam',
            name='start_ladder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_start_ladder', to='app.ladder', verbose_name='Лесенка к старту'),
        ),
    ]
