# Generated by Django 5.2 on 2025-05-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_historyparam_reaction_ladder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='subscribers_count',
            field=models.IntegerField(default=0, verbose_name='Кольчество аккаунтов'),
        ),
    ]
