# Generated by Django 5.2 on 2025-05-13 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_template_subscribers_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewparam',
            old_name='holliday',
            new_name='holiday',
        ),
        migrations.RemoveField(
            model_name='template',
            name='subscribers_count',
        ),
        migrations.AddField(
            model_name='task',
            name='subscribers_count',
            field=models.IntegerField(default=0, verbose_name='Кольчество аккаунтов'),
        ),
        migrations.AlterField(
            model_name='action',
            name='text',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Текст для прохождения теста'),
        ),
        migrations.AlterField(
            model_name='commentparam',
            name='ladder',
            field=models.CharField(default='', max_length=512, verbose_name='Лесенка для комментариев'),
        ),
        migrations.AlterField(
            model_name='historyparam',
            name='reaction_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество реакций'),
        ),
        migrations.AlterField(
            model_name='historyparam',
            name='view_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='reactionparam',
            name='ai_reactions',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_reactions', to='app.reaction', verbose_name='Реакции от ИИ'),
        ),
        migrations.AlterField(
            model_name='reactionparam',
            name='basic_reactions',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basic_reactions', to='app.reaction', verbose_name='Основные реакции'),
        ),
        migrations.AlterField(
            model_name='reactionparam',
            name='text_reactions',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_reactions', to='app.reaction', verbose_name='Реакции из текста'),
        ),
        migrations.AlterField(
            model_name='reactionparam',
            name='user_reactions',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reactions', to='app.reaction', verbose_name='Реакции от пользователей'),
        ),
    ]
