# Generated by Django 5.2 on 2025-05-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_holliday_viewparam_holiday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Название шаблона'),
        ),
    ]
